# tensor01

In [1]:
a = [1,2,3,4]

In [2]:
a[2]

3

In [4]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

# tensor02
Rank 秩 
Axes
Shape

In [5]:
# Each element along the first axis, is an array:
dd[0]

[1, 2, 3]

In [6]:
# Each element along the second axis, is a number:
dd[0][0]

1

In [7]:
import torch

In [9]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
t.shape

torch.Size([3, 3])

In [11]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
t.reshape(1,9).shape

torch.Size([1, 9])

# tensor03 CNN Tensor Shape Explained

In [ ]:
# Suppose we have the following shape [3, 1, 28, 28] for a given tensor. 
# Using the shape, we can determine that we have a batch of three images.
[Batch, Channels, Height, Width]

Batch size
Color channels
Height
Width

1.The shape of a CNN tensor input typically has a length of len(t.shape)
    4
2.For a given PyTorch CNN tensor input, which two axes can be used to denote the height and width coordinates of a particular pixel?
    The last two
3.For a given PyTorch CNN tensor input, the first axis denotes what information?
    The batch size
4.Consider a tensor with a shape of [3500, 3, 1920, 1200]. How many samples are contained in the tesnor?
    3500

# tensor04  PyTorch Tensors Explained

In [13]:
import torch
import numpy as np

In [14]:
t = torch.Tensor()
type(t)

torch.Tensor

In [15]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [16]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [17]:
# Tensor computations between tensors depend on the dtype and the device.
# 以下情况会报错
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

In [18]:
t1.device

device(type='cpu')

In [19]:
t2.device

device(type='cuda', index=0)

In [20]:
t1 + t2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

# Creating Tensors Using Data
torch.Tensor(data)
torch.tensor(data)
torch.as_tensor(data)
torch.from_numpy(data)

In [22]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [23]:
torch.Tensor(data) #数据类型发生了变化 变为浮点型

tensor([1., 2., 3.])

In [24]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

# Creation Options Without Data

In [27]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [28]:
torch.zeros([2,2])

tensor([[0., 0.],
        [0., 0.]])

In [29]:
torch.ones([2,2])

tensor([[1., 1.],
        [1., 1.]])

In [30]:
torch.rand([2,2])

tensor([[0.8969, 0.6448],
        [0.9392, 0.1710]])

# Quiz tensor04

In [ ]:
1.When programming neural networks, data preprocessing is often one of the first steps in the overall process, and one goal of data preprocessing is to transform the raw input data into
    tensor form
2.When performing tensor operations between two tensors in PyTorch, the two tensors must have the same 
    data type
3.In PyTorch, how do we transfer a tensor t to a GPU?
    t.cuda()
4.The error below indicates that an operation between two tensors failed because the tensors exist on two different devices.
  "RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'other'"
    True

# tensor05 Creating PyTorch Tensors For Deep Learning - Best Options

In [2]:
import torch
import numpy as np

In [3]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [4]:
t1 = torch.Tensor(data)# class constructor
t2 = torch.tensor(data)# factory function
t3 = torch.as_tensor(data)# factory function
t4 = torch.from_numpy(data)# factory function

In [5]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [6]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [7]:
torch.get_default_dtype()

torch.float32

In [ ]:
With torch.Tensor(), we are unable to pass a dtype to the constructor. 
This is an example of the torch.Tensor() constructor lacking in configuration options. 

In [10]:
torch.tensor(data, dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
difference between these alternative creation methods.
Sharing Memory For Performance: Copy Vs Share

In [11]:
data = np.array([1,2,3])
t1 = torch.Tensor(data)# class constructor
t2 = torch.tensor(data)# factory function
t3 = torch.as_tensor(data)# factory function
t4 = torch.from_numpy(data)# factory function

In [12]:
data[0] = 0
data[1] = 0
data[2] = 0

In [15]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [14]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


In [ ]:
Share Data                   Copy Data
torch.as_tensor()            torch.tensor() 
torch.from_numpy()           torch.Tensor()

In [ ]:
Given all of these details, these two are the best options:

torch.tensor()
torch.as_tensor()

The torch.tensor() call is the sort of go-to call, 
while torch.as_tensor() should be employed when tuning our code for performance.

Some things to keep in mind about memory sharing (it works where it can):

1.Since numpy.ndarray objects are allocated on the CPU, 
  the as_tensor() function must copy the data from the CPU to the GPU when a GPU is being used.
2.The memory sharing of as_tensor() doesn’t work with built-in Python data structures like lists.
3.The as_tensor() call requires developer knowledge of the sharing feature. 
  This is necessary so we don’t inadvertently make an unwanted change 
  in the underlying data without realizing the change impacts multiple objects.
4.The as_tensor() performance improvement will be greater 
  if there are a lot of back and forth operations between numpy.
  ndarray objects and tensor objects. However, if there is just a single load operation, 
  there shouldn’t be much impact from a performance perspective.

# Quiz tensor05

In [ ]:
1.Based on ease-of-use, configuration options, and better documentation, 
  which of the following is considered to be the go-to tensor creation function for every-day use?
    torch.tensor()
2.Suppose we have a variable called d. What is a major difference between 
  creating a tensor using torch.tensor(d) and creating a tensor using torch.as_tensor(d).
    torch.tensor(d) copies d and torch.as_tensor(d) shares memory with d.
3.Assume that data = np.array([1,2,3]). Which of the following tensor creation options makes use of a constructor?
    torch.Tensor(data)
4.Which of the following would create the 2D tensor below?
[
   [1,0,0]
  ,[0,1,0]
  ,[0,0,1]
]
    torch.eye(3)

# tensor 06 
# Flatten, Reshape, And Squeeze Explained - Tensors For Deep Learning With PyTorch

In [ ]:
We have the following high-level categories of operations:

Reshaping operations
Element-wise operations
Reduction operations
Access operations

In [16]:
import torch

In [17]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [18]:
t.size()

torch.Size([3, 4])

In [20]:
t.shape

torch.Size([3, 4])

In [21]:
len(t.shape)

2

In [22]:
torch.tensor(t.shape).prod()

tensor(12)

In [23]:
t.numel()

12

In [24]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [25]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [26]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [27]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [28]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [29]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [30]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [ ]:
Squeezing And Unsqueezing

In [31]:
print(t.reshape([1,12])) # original
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [32]:
print(t.reshape([1,12]).shape)# squeeze
print(t.reshape([1,12]).squeeze().shape)

torch.Size([1, 12])
torch.Size([12])


In [33]:
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))# unsqueeze
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [34]:
def flatten(t):
    t = t.reshape(1, -1) # -1意为自动计算元素个数 然后把元素排成一行
    t = t.squeeze()
    return t

In [35]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [38]:
flatten(t).size()

torch.Size([12])

In [36]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [39]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [40]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [41]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [42]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [43]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

# Quiz tensor06

In [ ]:
1.Q:Using the code below, determine the value of x that results in a correct implementation of the flatten tensor operation.
    def flatten(t):
        t = t.reshape(1, t.size()[0] * x)
        t = t.squeeze()
        return t
  A:t.size()[1]
2.Q:Using the code below, determine the operation on t that results in a correct implementation of the flatten tensor operation.
    def flatten(t):
        t = t.reshape(1, t.size()[0] * t.size()[1])
        t = ?
        return t
  A:t.squeeze()
3.Q:Using the code below as a reference, what's another way of expressing the value for the second argument 
    that's being passed to the reshape() method?
  A:t.numel()

# tensor07 
# CNN Flatten Operation Visualized - Tensor Batch Processing For Deep Learning

In [1]:
import torch

In [2]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [6]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [7]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [8]:
t = t.reshape(3,1,4,4)

In [9]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [10]:
t.reshape(1,-1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [13]:
t.reshape(1,-1).shape

torch.Size([1, 48])

In [11]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [14]:
t.reshape(1,-1)[0].shape

torch.Size([48])

In [12]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [15]:
t.reshape(-1).shape

torch.Size([48])

In [16]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [17]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [18]:
t.flatten(start_dim = 1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [19]:
t.flatten(start_dim = 1).shape

torch.Size([3, 16])

In [20]:
t.flatten(start_dim = 0)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [21]:
t.flatten(start_dim = 2)

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]])

In [22]:
t.flatten(start_dim = 3)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [ ]:
Flattening An RGB Image

In [24]:
r = torch.ones(1,2,2)
r

tensor([[[1., 1.],
         [1., 1.]]])

In [25]:
g = torch.ones(1,2,2) + 1
g

tensor([[[2., 2.],
         [2., 2.]]])

In [26]:
b = torch.ones(1,2,2) + 2

In [27]:
img = torch.cat(
    (r,g,b)
    ,dim=0
)

In [28]:
img

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [29]:
img.shape

torch.Size([3, 2, 2])

In [30]:
img.flatten(start_dim=0)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [31]:
img.flatten(start_dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

# Quiz tensor07

In [ ]:
1.Q:A tensor flatten operation is a common operation inside convolutional neural networks. 
    This is because convolutional layer outputs that are passed to fully connected layers must be _______________ 
    before being passed to a fully connected layer.
  A:flattened
2.Q:A flatten operation is a specific type of _______________ where by all of the axes are smooshed or squashed together.
  A:reshaping operation
3.Q:To flatten a tensor, we need to have at least _______________ axes. 
    This makes it so that we are starting with something that is not already flat.
  A:two



# tensor08 
# Tensors For Deep Learning - Broadcasting And Element-Wise Operations With PyTorch


In [ ]:
Reshaping operations
!Element-wise operations!
Reduction operations
Access operations

In [32]:
import torch
import numpy as np

In [33]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype = torch.float32)
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [34]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [35]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [36]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [37]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [38]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [39]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [40]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [41]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [42]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [43]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [ ]:
This means the scalar value is transformed into a rank-2 tensor just like t1, 
and just like that, the shapes match and the element-wise rule of having 
the same shape is back in play. This is all under the hood of course.

This piece of code here paints the picture so to speak. This

In [44]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [ ]:
is really this:

In [45]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

<ipython-input-45-a013077ff9d7>:1: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:141.)
  t1 + torch.tensor(


tensor([[3., 4.],
        [5., 6.]])

In [46]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [47]:
t1.shape

torch.Size([2, 2])

In [48]:
t2.shape

torch.Size([2])

In [49]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [50]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

# Quiz tensor08

In [ ]:
1.Q:An _______________ operation is an operation between two tensors that operates on corresponding elements within the respective tensors.
  A:element-wise
2.Q:Two elements within a tensor are said to be _______________ if the two elements occupy the same position within the tensor.
  A:corresponding
3.Q:The position of an element inside a tensor is determined by the _______________ used to locate the respective element.
  A:indexes
4.Q:_______________ describes how tensors with different shapes are treated during element-wise operations.
  A:Broadcasting


# tensor09 Code For Deep Learning - ArgMax And Reduction Tensor Ops

In [ ]:
Reshaping operations
Element-wise operations
!Reduction operations!
!Access operations!

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [3]:
t.sum()

tensor(8.)

In [4]:
t.numel()

9

In [5]:
t.sum().numel()

1

In [6]:
t.sum().numel() < t.numel()

True

In [7]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [8]:
t.sum(dim = 0)

tensor([6., 6., 6., 6.])

In [9]:
t[0]

tensor([1., 1., 1., 1.])

In [10]:
t[1]

tensor([2., 2., 2., 2.])

In [11]:
t[2]

tensor([3., 3., 3., 3.])

In [12]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

In [13]:
t[0].sum()

tensor(4.)

In [14]:
t[1].sum()

tensor(8.)

In [15]:
t[2].sum()

tensor(12.)

In [16]:
t.sum(dim = 1)

tensor([ 4.,  8., 12.])

## ArgMax

In [17]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [18]:
t.max()

tensor(5.)

In [19]:
t.argmax()

tensor(11)

In [20]:
t.flattern()

AttributeError: 'Tensor' object has no attribute 'flattern'

In [21]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [22]:
t.max(dim = 0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [23]:
t.max(dim = 0)[0]

tensor([4., 3., 3., 5.])

In [24]:
t.max(dim = 0)[1]

tensor([2, 1, 1, 2])

In [25]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [26]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [27]:
t.argmax(dim=1)

tensor([3, 2, 3])

In [28]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [29]:
t.mean()

tensor(5.)

In [30]:
t.mean().item()

5.0

In [31]:
t.mean(dim=0)

tensor([4., 5., 6.])

In [32]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [33]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)